### ISSUE TITLE
Folding of blocks is wrong

### ISSUE THREAD

**Issue by halostatue** [sunaku/vim-ruby-minitest#10]
Minitest files are just ruby files, and the changes to vim-ruby-minitest breaks folding of blocks if it is already supported, as with vim-ruby’s folding. Basically, if I have:

```ruby
describe Foo do
  describe 'something' do
    it 'does something' do
      …
    end
  end
end
```

The folding *should* be:

```ruby
describe Foo do
  describe 'something' do
    + it 'does something' do----------
  end
end
```

The folding *actually* is:

```ruby
describe Foo do
  describe 'something' do
    + it 'does something' do----------
```

**Comment by halostatue** [comment]
I have fixed this locally with:

```diff
--- i/after/syntax/ruby/minitest.vim
+++ w/after/syntax/ruby/minitest.vim
@@ -2,7 +2,10 @@ let s:fold = get(b:, 'ruby_minitest_fold', get(g:, 'ruby_minitest_fold'))
 let s:i = ''
 
 if !has('folding') || empty(s:fold)
-  let s:fold = ''
+  syntax keyword rubyTestMethod
+        \ describe
+        \ it
+  finish
 else
   let s:fold = ' fold'
 endif
```

**Comment by sunaku** [comment]
Thanks @halostatue. :sparkling_heart: Now that you have a patch how about submitting a PR? :smirk_cat:

**Comment by halostatue** [comment]
Sure. I just wanted to show it before a PR was made because it essentially *reverts* this change in the event that `ruby_minitest_fold` has not been set.

**Comment by halostatue** [comment]
I also wanted to point out that it *may not* be ideal if you have `ruby_minitest_fold` enabled but have Ruby folding in other ways.

**Comment by sunaku** [comment]
In that case, @bootleq (as the original contributed the folding definition) should review this change. :cop:

**Comment by bootleq** [comment]
I second this change, syntax folding of these 2 plugins don't work well together.
Thanks @halostatue, I suggest also modify doc to mention incompatibility with vim-ruby.

**Comment by halostatue** [comment]
OK. Let me work up a PR for this based on my local change.
=
